spring.application.name=chatting-app
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/chatting_app

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
app.auth.token-hours=168
